[Desktop Entry]
Name=wyrdoaks-green
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=wyrdoaks-green
MetacityTheme=wyrdoaks-green
IconTheme=(malys_EXcelenT)(01)
GtkColorScheme=fg_color:#d4d4d4d4d4d4,bg_color:#333333333333,text_color:#d4d4d4d4d4d4,base_color:#474747474747,selected_fg_color:#b5b5bfbfb1b1,selected_bg_color:#0b0b1e1e0000,tooltip_fg_color:#000000000000,tooltip_bg_color:#f5f5f5f5b5b5
CursorTheme=default
CursorSize=18
NotificationTheme=standard
